language: java

sudo: false

jdk:
  - oraclejdk8

branches:
  only:
    - develop

script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

