language: java

sudo: false

jdk:
  - openjdk11
  - oraclejdk11

branches:
  only:
    - develop


script: mvn install -Dlogfile.name="cy3sbml.log" -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

