language: java

sudo: false

jdk:
  - oraclejdk8

branches:
  only:
    - develop


script: mvn install -Dlogfile.name="cy3sbml.log" -Dmaven.javadoc.skip=true -DskipTests=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

